apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"local-vol-srv-k8ssandra"},"spec":{"accessModes":["ReadWriteOnce","ReadWriteMany"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/srv/k8ssandra"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"manual"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2025-10-30T13:29:35Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: local-vol-srv-k8ssandra
  resourceVersion: "4501"
  uid: c08f3744-8bc1-4696-8e28-0dd47e089fa9
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: local-pvc-srv-k8ssandra
    namespace: default
    resourceVersion: "4499"
    uid: a80e5122-4ba3-4c91-8137-d6fd5b502d1a
  hostPath:
    path: /srv/k8ssandra
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2025-10-30T13:31:57Z"
  phase: Bound
