apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"open-webui-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"manual-open-webui","volumeName":"open-webui-pv"}}
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2026-04-28T15:51:56Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: open-webui-data
  namespace: default
  resourceVersion: "46654662"
  uid: b82f755a-8153-4dd7-bb20-11336cfb0967
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual-open-webui
  volumeMode: Filesystem
  volumeName: open-webui-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
