apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"rqlite-svc-internal","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"port":4001,"protocol":"TCP","targetPort":4001}],"publishNotReadyAddresses":true,"selector":{"app":"rqlite"}}}
  creationTimestamp: "2025-10-30T13:35:15Z"
  name: rqlite-svc-internal
  namespace: default
  resourceVersion: "5162"
  uid: 3660c86c-2ba3-4778-9c10-eb3180881388
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  publishNotReadyAddresses: true
  selector:
    app: rqlite
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
