apiVersion: v1

kind: Service

metadata:
  labels:
    app: jaeger
  name: jaeger-cassandra-query

spec:
  ports:
  - name: http-query
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: grpc-query
    port: 16685
    protocol: TCP
    targetPort: 16685
  selector:
    app: jaeger
  type: LoadBalancer
