apiVersion: jaegertracing.io/v1

kind: Jaeger

metadata:
  name: jaeger-cassandra

spec:
  strategy: allInOne
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra-internal
        keyspace: jaeger
    cassandraCreateSchema:
      enabled: false
