apiVersion: v1
kind: Pod
metadata:
  name: fedora-debug
  labels:
    app: fedora-debug
spec:
  containers:
  - image: localhost:32000/fedora-debug:1
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: fedora-debug
  restartPolicy: Always
