apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-vol-srv-k8ssandra
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/k8ssandra

