apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-srv-k8ssandra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "local-vol-srv-k8ssandra"

