replicaCount: 3

serviceName: nginx-helm-service
deploymentName: nginx-helm-deployment
pvName: nginx-helm-pv-storageame
pvClaimName: local-pvc-srv-k8ssandra

image:
  repository: nginx
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  mountPath: "/usr/share"

