apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-macbook-pro-2010
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /src/nfs
    server: macbook-pro-2010

