# IMPORTANT: Needed to be done from microk8s machine(?)

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-macbook-pro-2010
provisioner: nfs.csi.k8s.io
parameters:
  server: macbook-pro-2010
  share: /srv/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1

